### ISSUE TITLE
USB08 – Ver PL Disponíveis

### ISSUE THREAD

**Issue by kleberbritomoreira10** [fga-gpp-mds/2018.1-VoxPop-API#23]
# USB08 – Ver PL Disponíveis

### Descrição:
Eu, como usuário desejo ver lista de PL disponíveis (dashboard) para que eu possa ter acesso a qualquer PL da aplicação

## Critérios de aceitação
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by affbedran** [comment]
Done.
