### ISSUE TITLE
TS04 - Endpoint para Contato 

### ISSUE THREAD

**Issue by Eduardolimr** [fga-gpp-mds/2018.1-VoxPop-API#94]
# TS04 - Endpoint para Contato

### Descrição:
Eu, como desenvolvedor, quero um endpoint para receber as mensagens de usuários por meio da página de contato.

## Comportamento esperado
CRUD comum para os campos da mensagem da página contact-us: Tópico, Assunto e Mensagem.

## Possível solução
Criar um endpoint para preenchimento dos campos da mensagem do usuário no banco de dados do projeto.

## Critérios de aceitação

- [ ] Criar o endpoint de contato na API.

**Comment by mateusdemorais** [comment]
Acabei comentando na issue do front, vou deixar o link do comentário aqui só pra registro:
https://github.com/fga-gpp-mds/2018.1-VoxPop-WebApp/issues/145#issuecomment-397485626

Gostaria de pedir também que o campo `email` da model seja alterado para `EmailField`.

Referência:
https://docs.djangoproject.com/en/2.0/ref/models/fields/#emailfield
